language: php

php:
  - 7.0
env:
  - SYMFONY_VERSION=3.2.*

before_script:
  - travis_retry composer self-update

install:
  - composer require symfony/framework-bundle:${SYMFONY_VERSION}

addons:
  code_climate:
    repo_token: 4ae0e9a441e00d34b3400eb6ff19abe30d786090cb77630caf02ab086e87f9ee

script:
  - mkdir -p build/logs
  - phpunit --coverage-text --coverage-clover=coverage.clover
  - phpunit --coverage-clover build/logs/clover.xml

after_success:
  - vendor/bin/test-reporter